services:
  postgresql:
    # https://hub.docker.com/_/postgres
    image: postgres:17-alpine
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: prisma-queue
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
