
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QueueJob` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QueueJob
 * 
 */
export type QueueJobModel = runtime.Types.Result.DefaultSelection<Prisma.$QueueJobPayload>

export type AggregateQueueJob = {
  _count: QueueJobCountAggregateOutputType | null
  _avg: QueueJobAvgAggregateOutputType | null
  _sum: QueueJobSumAggregateOutputType | null
  _min: QueueJobMinAggregateOutputType | null
  _max: QueueJobMaxAggregateOutputType | null
}

export type QueueJobAvgAggregateOutputType = {
  id: number | null
  progress: number | null
  priority: number | null
  attempts: number | null
  maxAttempts: number | null
}

export type QueueJobSumAggregateOutputType = {
  id: bigint | null
  progress: number | null
  priority: number | null
  attempts: number | null
  maxAttempts: number | null
}

export type QueueJobMinAggregateOutputType = {
  id: bigint | null
  queue: string | null
  key: string | null
  cron: string | null
  progress: number | null
  priority: number | null
  attempts: number | null
  maxAttempts: number | null
  runAt: Date | null
  notBefore: Date | null
  finishedAt: Date | null
  processedAt: Date | null
  failedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QueueJobMaxAggregateOutputType = {
  id: bigint | null
  queue: string | null
  key: string | null
  cron: string | null
  progress: number | null
  priority: number | null
  attempts: number | null
  maxAttempts: number | null
  runAt: Date | null
  notBefore: Date | null
  finishedAt: Date | null
  processedAt: Date | null
  failedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type QueueJobCountAggregateOutputType = {
  id: number
  queue: number
  key: number
  cron: number
  payload: number
  result: number
  error: number
  progress: number
  priority: number
  attempts: number
  maxAttempts: number
  runAt: number
  notBefore: number
  finishedAt: number
  processedAt: number
  failedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type QueueJobAvgAggregateInputType = {
  id?: true
  progress?: true
  priority?: true
  attempts?: true
  maxAttempts?: true
}

export type QueueJobSumAggregateInputType = {
  id?: true
  progress?: true
  priority?: true
  attempts?: true
  maxAttempts?: true
}

export type QueueJobMinAggregateInputType = {
  id?: true
  queue?: true
  key?: true
  cron?: true
  progress?: true
  priority?: true
  attempts?: true
  maxAttempts?: true
  runAt?: true
  notBefore?: true
  finishedAt?: true
  processedAt?: true
  failedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type QueueJobMaxAggregateInputType = {
  id?: true
  queue?: true
  key?: true
  cron?: true
  progress?: true
  priority?: true
  attempts?: true
  maxAttempts?: true
  runAt?: true
  notBefore?: true
  finishedAt?: true
  processedAt?: true
  failedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type QueueJobCountAggregateInputType = {
  id?: true
  queue?: true
  key?: true
  cron?: true
  payload?: true
  result?: true
  error?: true
  progress?: true
  priority?: true
  attempts?: true
  maxAttempts?: true
  runAt?: true
  notBefore?: true
  finishedAt?: true
  processedAt?: true
  failedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type QueueJobAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QueueJob to aggregate.
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueJobs to fetch.
   */
  orderBy?: Prisma.QueueJobOrderByWithRelationInput | Prisma.QueueJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QueueJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QueueJobs
  **/
  _count?: true | QueueJobCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QueueJobAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QueueJobSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QueueJobMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QueueJobMaxAggregateInputType
}

export type GetQueueJobAggregateType<T extends QueueJobAggregateArgs> = {
      [P in keyof T & keyof AggregateQueueJob]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQueueJob[P]>
    : Prisma.GetScalarType<T[P], AggregateQueueJob[P]>
}




export type QueueJobGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QueueJobWhereInput
  orderBy?: Prisma.QueueJobOrderByWithAggregationInput | Prisma.QueueJobOrderByWithAggregationInput[]
  by: Prisma.QueueJobScalarFieldEnum[] | Prisma.QueueJobScalarFieldEnum
  having?: Prisma.QueueJobScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QueueJobCountAggregateInputType | true
  _avg?: QueueJobAvgAggregateInputType
  _sum?: QueueJobSumAggregateInputType
  _min?: QueueJobMinAggregateInputType
  _max?: QueueJobMaxAggregateInputType
}

export type QueueJobGroupByOutputType = {
  id: bigint
  queue: string
  key: string | null
  cron: string | null
  payload: runtime.JsonValue | null
  result: runtime.JsonValue | null
  error: runtime.JsonValue | null
  progress: number
  priority: number
  attempts: number
  maxAttempts: number | null
  runAt: Date
  notBefore: Date | null
  finishedAt: Date | null
  processedAt: Date | null
  failedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: QueueJobCountAggregateOutputType | null
  _avg: QueueJobAvgAggregateOutputType | null
  _sum: QueueJobSumAggregateOutputType | null
  _min: QueueJobMinAggregateOutputType | null
  _max: QueueJobMaxAggregateOutputType | null
}

type GetQueueJobGroupByPayload<T extends QueueJobGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QueueJobGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QueueJobGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QueueJobGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QueueJobGroupByOutputType[P]>
      }
    >
  >



export type QueueJobWhereInput = {
  AND?: Prisma.QueueJobWhereInput | Prisma.QueueJobWhereInput[]
  OR?: Prisma.QueueJobWhereInput[]
  NOT?: Prisma.QueueJobWhereInput | Prisma.QueueJobWhereInput[]
  id?: Prisma.BigIntFilter<"QueueJob"> | bigint | number
  queue?: Prisma.StringFilter<"QueueJob"> | string
  key?: Prisma.StringNullableFilter<"QueueJob"> | string | null
  cron?: Prisma.StringNullableFilter<"QueueJob"> | string | null
  payload?: Prisma.JsonNullableFilter<"QueueJob">
  result?: Prisma.JsonNullableFilter<"QueueJob">
  error?: Prisma.JsonNullableFilter<"QueueJob">
  progress?: Prisma.IntFilter<"QueueJob"> | number
  priority?: Prisma.IntFilter<"QueueJob"> | number
  attempts?: Prisma.IntFilter<"QueueJob"> | number
  maxAttempts?: Prisma.IntNullableFilter<"QueueJob"> | number | null
  runAt?: Prisma.DateTimeFilter<"QueueJob"> | Date | string
  notBefore?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  finishedAt?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  processedAt?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  failedAt?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"QueueJob"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QueueJob"> | Date | string
}

export type QueueJobOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  queue?: Prisma.SortOrder
  key?: Prisma.SortOrderInput | Prisma.SortOrder
  cron?: Prisma.SortOrderInput | Prisma.SortOrder
  payload?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrderInput | Prisma.SortOrder
  runAt?: Prisma.SortOrder
  notBefore?: Prisma.SortOrderInput | Prisma.SortOrder
  finishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  failedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QueueJobWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  key_runAt?: Prisma.QueueJobKeyRunAtCompoundUniqueInput
  AND?: Prisma.QueueJobWhereInput | Prisma.QueueJobWhereInput[]
  OR?: Prisma.QueueJobWhereInput[]
  NOT?: Prisma.QueueJobWhereInput | Prisma.QueueJobWhereInput[]
  queue?: Prisma.StringFilter<"QueueJob"> | string
  key?: Prisma.StringNullableFilter<"QueueJob"> | string | null
  cron?: Prisma.StringNullableFilter<"QueueJob"> | string | null
  payload?: Prisma.JsonNullableFilter<"QueueJob">
  result?: Prisma.JsonNullableFilter<"QueueJob">
  error?: Prisma.JsonNullableFilter<"QueueJob">
  progress?: Prisma.IntFilter<"QueueJob"> | number
  priority?: Prisma.IntFilter<"QueueJob"> | number
  attempts?: Prisma.IntFilter<"QueueJob"> | number
  maxAttempts?: Prisma.IntNullableFilter<"QueueJob"> | number | null
  runAt?: Prisma.DateTimeFilter<"QueueJob"> | Date | string
  notBefore?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  finishedAt?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  processedAt?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  failedAt?: Prisma.DateTimeNullableFilter<"QueueJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"QueueJob"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"QueueJob"> | Date | string
}, "id" | "key_runAt">

export type QueueJobOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  queue?: Prisma.SortOrder
  key?: Prisma.SortOrderInput | Prisma.SortOrder
  cron?: Prisma.SortOrderInput | Prisma.SortOrder
  payload?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrderInput | Prisma.SortOrder
  runAt?: Prisma.SortOrder
  notBefore?: Prisma.SortOrderInput | Prisma.SortOrder
  finishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  failedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.QueueJobCountOrderByAggregateInput
  _avg?: Prisma.QueueJobAvgOrderByAggregateInput
  _max?: Prisma.QueueJobMaxOrderByAggregateInput
  _min?: Prisma.QueueJobMinOrderByAggregateInput
  _sum?: Prisma.QueueJobSumOrderByAggregateInput
}

export type QueueJobScalarWhereWithAggregatesInput = {
  AND?: Prisma.QueueJobScalarWhereWithAggregatesInput | Prisma.QueueJobScalarWhereWithAggregatesInput[]
  OR?: Prisma.QueueJobScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QueueJobScalarWhereWithAggregatesInput | Prisma.QueueJobScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"QueueJob"> | bigint | number
  queue?: Prisma.StringWithAggregatesFilter<"QueueJob"> | string
  key?: Prisma.StringNullableWithAggregatesFilter<"QueueJob"> | string | null
  cron?: Prisma.StringNullableWithAggregatesFilter<"QueueJob"> | string | null
  payload?: Prisma.JsonNullableWithAggregatesFilter<"QueueJob">
  result?: Prisma.JsonNullableWithAggregatesFilter<"QueueJob">
  error?: Prisma.JsonNullableWithAggregatesFilter<"QueueJob">
  progress?: Prisma.IntWithAggregatesFilter<"QueueJob"> | number
  priority?: Prisma.IntWithAggregatesFilter<"QueueJob"> | number
  attempts?: Prisma.IntWithAggregatesFilter<"QueueJob"> | number
  maxAttempts?: Prisma.IntNullableWithAggregatesFilter<"QueueJob"> | number | null
  runAt?: Prisma.DateTimeWithAggregatesFilter<"QueueJob"> | Date | string
  notBefore?: Prisma.DateTimeNullableWithAggregatesFilter<"QueueJob"> | Date | string | null
  finishedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"QueueJob"> | Date | string | null
  processedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"QueueJob"> | Date | string | null
  failedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"QueueJob"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QueueJob"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"QueueJob"> | Date | string
}

export type QueueJobCreateInput = {
  id?: bigint | number
  queue: string
  key?: string | null
  cron?: string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: number
  priority?: number
  attempts?: number
  maxAttempts?: number | null
  runAt?: Date | string
  notBefore?: Date | string | null
  finishedAt?: Date | string | null
  processedAt?: Date | string | null
  failedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QueueJobUncheckedCreateInput = {
  id?: bigint | number
  queue: string
  key?: string | null
  cron?: string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: number
  priority?: number
  attempts?: number
  maxAttempts?: number | null
  runAt?: Date | string
  notBefore?: Date | string | null
  finishedAt?: Date | string | null
  processedAt?: Date | string | null
  failedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QueueJobUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  queue?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  maxAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  runAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notBefore?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QueueJobUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  queue?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  maxAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  runAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notBefore?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QueueJobCreateManyInput = {
  id?: bigint | number
  queue: string
  key?: string | null
  cron?: string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: number
  priority?: number
  attempts?: number
  maxAttempts?: number | null
  runAt?: Date | string
  notBefore?: Date | string | null
  finishedAt?: Date | string | null
  processedAt?: Date | string | null
  failedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type QueueJobUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  queue?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  maxAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  runAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notBefore?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QueueJobUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  queue?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  error?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  maxAttempts?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  runAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  notBefore?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  failedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QueueJobKeyRunAtCompoundUniqueInput = {
  key: string
  runAt: Date | string
}

export type QueueJobCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  queue?: Prisma.SortOrder
  key?: Prisma.SortOrder
  cron?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  result?: Prisma.SortOrder
  error?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrder
  runAt?: Prisma.SortOrder
  notBefore?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  failedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QueueJobAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrder
}

export type QueueJobMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  queue?: Prisma.SortOrder
  key?: Prisma.SortOrder
  cron?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrder
  runAt?: Prisma.SortOrder
  notBefore?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  failedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QueueJobMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  queue?: Prisma.SortOrder
  key?: Prisma.SortOrder
  cron?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrder
  runAt?: Prisma.SortOrder
  notBefore?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
  failedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type QueueJobSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
  maxAttempts?: Prisma.SortOrder
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type QueueJobSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  queue?: boolean
  key?: boolean
  cron?: boolean
  payload?: boolean
  result?: boolean
  error?: boolean
  progress?: boolean
  priority?: boolean
  attempts?: boolean
  maxAttempts?: boolean
  runAt?: boolean
  notBefore?: boolean
  finishedAt?: boolean
  processedAt?: boolean
  failedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["queueJob"]>

export type QueueJobSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  queue?: boolean
  key?: boolean
  cron?: boolean
  payload?: boolean
  result?: boolean
  error?: boolean
  progress?: boolean
  priority?: boolean
  attempts?: boolean
  maxAttempts?: boolean
  runAt?: boolean
  notBefore?: boolean
  finishedAt?: boolean
  processedAt?: boolean
  failedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["queueJob"]>

export type QueueJobSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  queue?: boolean
  key?: boolean
  cron?: boolean
  payload?: boolean
  result?: boolean
  error?: boolean
  progress?: boolean
  priority?: boolean
  attempts?: boolean
  maxAttempts?: boolean
  runAt?: boolean
  notBefore?: boolean
  finishedAt?: boolean
  processedAt?: boolean
  failedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["queueJob"]>

export type QueueJobSelectScalar = {
  id?: boolean
  queue?: boolean
  key?: boolean
  cron?: boolean
  payload?: boolean
  result?: boolean
  error?: boolean
  progress?: boolean
  priority?: boolean
  attempts?: boolean
  maxAttempts?: boolean
  runAt?: boolean
  notBefore?: boolean
  finishedAt?: boolean
  processedAt?: boolean
  failedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type QueueJobOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "queue" | "key" | "cron" | "payload" | "result" | "error" | "progress" | "priority" | "attempts" | "maxAttempts" | "runAt" | "notBefore" | "finishedAt" | "processedAt" | "failedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["queueJob"]>

export type $QueueJobPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QueueJob"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    queue: string
    key: string | null
    cron: string | null
    payload: runtime.JsonValue | null
    result: runtime.JsonValue | null
    error: runtime.JsonValue | null
    progress: number
    priority: number
    attempts: number
    maxAttempts: number | null
    runAt: Date
    notBefore: Date | null
    finishedAt: Date | null
    processedAt: Date | null
    failedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["queueJob"]>
  composites: {}
}

export type QueueJobGetPayload<S extends boolean | null | undefined | QueueJobDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QueueJobPayload, S>

export type QueueJobCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QueueJobFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QueueJobCountAggregateInputType | true
  }

export interface QueueJobDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QueueJob'], meta: { name: 'QueueJob' } }
  /**
   * Find zero or one QueueJob that matches the filter.
   * @param {QueueJobFindUniqueArgs} args - Arguments to find a QueueJob
   * @example
   * // Get one QueueJob
   * const queueJob = await prisma.queueJob.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QueueJobFindUniqueArgs>(args: Prisma.SelectSubset<T, QueueJobFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QueueJob that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QueueJobFindUniqueOrThrowArgs} args - Arguments to find a QueueJob
   * @example
   * // Get one QueueJob
   * const queueJob = await prisma.queueJob.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QueueJobFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QueueJobFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QueueJob that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobFindFirstArgs} args - Arguments to find a QueueJob
   * @example
   * // Get one QueueJob
   * const queueJob = await prisma.queueJob.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QueueJobFindFirstArgs>(args?: Prisma.SelectSubset<T, QueueJobFindFirstArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QueueJob that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobFindFirstOrThrowArgs} args - Arguments to find a QueueJob
   * @example
   * // Get one QueueJob
   * const queueJob = await prisma.queueJob.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QueueJobFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QueueJobFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QueueJobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QueueJobs
   * const queueJobs = await prisma.queueJob.findMany()
   * 
   * // Get first 10 QueueJobs
   * const queueJobs = await prisma.queueJob.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const queueJobWithIdOnly = await prisma.queueJob.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QueueJobFindManyArgs>(args?: Prisma.SelectSubset<T, QueueJobFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QueueJob.
   * @param {QueueJobCreateArgs} args - Arguments to create a QueueJob.
   * @example
   * // Create one QueueJob
   * const QueueJob = await prisma.queueJob.create({
   *   data: {
   *     // ... data to create a QueueJob
   *   }
   * })
   * 
   */
  create<T extends QueueJobCreateArgs>(args: Prisma.SelectSubset<T, QueueJobCreateArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QueueJobs.
   * @param {QueueJobCreateManyArgs} args - Arguments to create many QueueJobs.
   * @example
   * // Create many QueueJobs
   * const queueJob = await prisma.queueJob.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QueueJobCreateManyArgs>(args?: Prisma.SelectSubset<T, QueueJobCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QueueJobs and returns the data saved in the database.
   * @param {QueueJobCreateManyAndReturnArgs} args - Arguments to create many QueueJobs.
   * @example
   * // Create many QueueJobs
   * const queueJob = await prisma.queueJob.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QueueJobs and only return the `id`
   * const queueJobWithIdOnly = await prisma.queueJob.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QueueJobCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QueueJobCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QueueJob.
   * @param {QueueJobDeleteArgs} args - Arguments to delete one QueueJob.
   * @example
   * // Delete one QueueJob
   * const QueueJob = await prisma.queueJob.delete({
   *   where: {
   *     // ... filter to delete one QueueJob
   *   }
   * })
   * 
   */
  delete<T extends QueueJobDeleteArgs>(args: Prisma.SelectSubset<T, QueueJobDeleteArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QueueJob.
   * @param {QueueJobUpdateArgs} args - Arguments to update one QueueJob.
   * @example
   * // Update one QueueJob
   * const queueJob = await prisma.queueJob.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QueueJobUpdateArgs>(args: Prisma.SelectSubset<T, QueueJobUpdateArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QueueJobs.
   * @param {QueueJobDeleteManyArgs} args - Arguments to filter QueueJobs to delete.
   * @example
   * // Delete a few QueueJobs
   * const { count } = await prisma.queueJob.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QueueJobDeleteManyArgs>(args?: Prisma.SelectSubset<T, QueueJobDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QueueJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QueueJobs
   * const queueJob = await prisma.queueJob.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QueueJobUpdateManyArgs>(args: Prisma.SelectSubset<T, QueueJobUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QueueJobs and returns the data updated in the database.
   * @param {QueueJobUpdateManyAndReturnArgs} args - Arguments to update many QueueJobs.
   * @example
   * // Update many QueueJobs
   * const queueJob = await prisma.queueJob.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QueueJobs and only return the `id`
   * const queueJobWithIdOnly = await prisma.queueJob.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QueueJobUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QueueJobUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QueueJob.
   * @param {QueueJobUpsertArgs} args - Arguments to update or create a QueueJob.
   * @example
   * // Update or create a QueueJob
   * const queueJob = await prisma.queueJob.upsert({
   *   create: {
   *     // ... data to create a QueueJob
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QueueJob we want to update
   *   }
   * })
   */
  upsert<T extends QueueJobUpsertArgs>(args: Prisma.SelectSubset<T, QueueJobUpsertArgs<ExtArgs>>): Prisma.Prisma__QueueJobClient<runtime.Types.Result.GetResult<Prisma.$QueueJobPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QueueJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobCountArgs} args - Arguments to filter QueueJobs to count.
   * @example
   * // Count the number of QueueJobs
   * const count = await prisma.queueJob.count({
   *   where: {
   *     // ... the filter for the QueueJobs we want to count
   *   }
   * })
  **/
  count<T extends QueueJobCountArgs>(
    args?: Prisma.Subset<T, QueueJobCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QueueJobCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QueueJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QueueJobAggregateArgs>(args: Prisma.Subset<T, QueueJobAggregateArgs>): Prisma.PrismaPromise<GetQueueJobAggregateType<T>>

  /**
   * Group by QueueJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QueueJobGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QueueJobGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QueueJobGroupByArgs['orderBy'] }
      : { orderBy?: QueueJobGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QueueJobGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQueueJobGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QueueJob model
 */
readonly fields: QueueJobFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QueueJob.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QueueJobClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QueueJob model
 */
export interface QueueJobFieldRefs {
  readonly id: Prisma.FieldRef<"QueueJob", 'BigInt'>
  readonly queue: Prisma.FieldRef<"QueueJob", 'String'>
  readonly key: Prisma.FieldRef<"QueueJob", 'String'>
  readonly cron: Prisma.FieldRef<"QueueJob", 'String'>
  readonly payload: Prisma.FieldRef<"QueueJob", 'Json'>
  readonly result: Prisma.FieldRef<"QueueJob", 'Json'>
  readonly error: Prisma.FieldRef<"QueueJob", 'Json'>
  readonly progress: Prisma.FieldRef<"QueueJob", 'Int'>
  readonly priority: Prisma.FieldRef<"QueueJob", 'Int'>
  readonly attempts: Prisma.FieldRef<"QueueJob", 'Int'>
  readonly maxAttempts: Prisma.FieldRef<"QueueJob", 'Int'>
  readonly runAt: Prisma.FieldRef<"QueueJob", 'DateTime'>
  readonly notBefore: Prisma.FieldRef<"QueueJob", 'DateTime'>
  readonly finishedAt: Prisma.FieldRef<"QueueJob", 'DateTime'>
  readonly processedAt: Prisma.FieldRef<"QueueJob", 'DateTime'>
  readonly failedAt: Prisma.FieldRef<"QueueJob", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"QueueJob", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"QueueJob", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QueueJob findUnique
 */
export type QueueJobFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * Filter, which QueueJob to fetch.
   */
  where: Prisma.QueueJobWhereUniqueInput
}

/**
 * QueueJob findUniqueOrThrow
 */
export type QueueJobFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * Filter, which QueueJob to fetch.
   */
  where: Prisma.QueueJobWhereUniqueInput
}

/**
 * QueueJob findFirst
 */
export type QueueJobFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * Filter, which QueueJob to fetch.
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueJobs to fetch.
   */
  orderBy?: Prisma.QueueJobOrderByWithRelationInput | Prisma.QueueJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QueueJobs.
   */
  cursor?: Prisma.QueueJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QueueJobs.
   */
  distinct?: Prisma.QueueJobScalarFieldEnum | Prisma.QueueJobScalarFieldEnum[]
}

/**
 * QueueJob findFirstOrThrow
 */
export type QueueJobFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * Filter, which QueueJob to fetch.
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueJobs to fetch.
   */
  orderBy?: Prisma.QueueJobOrderByWithRelationInput | Prisma.QueueJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QueueJobs.
   */
  cursor?: Prisma.QueueJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QueueJobs.
   */
  distinct?: Prisma.QueueJobScalarFieldEnum | Prisma.QueueJobScalarFieldEnum[]
}

/**
 * QueueJob findMany
 */
export type QueueJobFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * Filter, which QueueJobs to fetch.
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QueueJobs to fetch.
   */
  orderBy?: Prisma.QueueJobOrderByWithRelationInput | Prisma.QueueJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QueueJobs.
   */
  cursor?: Prisma.QueueJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QueueJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QueueJobs.
   */
  skip?: number
  distinct?: Prisma.QueueJobScalarFieldEnum | Prisma.QueueJobScalarFieldEnum[]
}

/**
 * QueueJob create
 */
export type QueueJobCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * The data needed to create a QueueJob.
   */
  data: Prisma.XOR<Prisma.QueueJobCreateInput, Prisma.QueueJobUncheckedCreateInput>
}

/**
 * QueueJob createMany
 */
export type QueueJobCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QueueJobs.
   */
  data: Prisma.QueueJobCreateManyInput | Prisma.QueueJobCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QueueJob createManyAndReturn
 */
export type QueueJobCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * The data used to create many QueueJobs.
   */
  data: Prisma.QueueJobCreateManyInput | Prisma.QueueJobCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QueueJob update
 */
export type QueueJobUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * The data needed to update a QueueJob.
   */
  data: Prisma.XOR<Prisma.QueueJobUpdateInput, Prisma.QueueJobUncheckedUpdateInput>
  /**
   * Choose, which QueueJob to update.
   */
  where: Prisma.QueueJobWhereUniqueInput
}

/**
 * QueueJob updateMany
 */
export type QueueJobUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QueueJobs.
   */
  data: Prisma.XOR<Prisma.QueueJobUpdateManyMutationInput, Prisma.QueueJobUncheckedUpdateManyInput>
  /**
   * Filter which QueueJobs to update
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * Limit how many QueueJobs to update.
   */
  limit?: number
}

/**
 * QueueJob updateManyAndReturn
 */
export type QueueJobUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * The data used to update QueueJobs.
   */
  data: Prisma.XOR<Prisma.QueueJobUpdateManyMutationInput, Prisma.QueueJobUncheckedUpdateManyInput>
  /**
   * Filter which QueueJobs to update
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * Limit how many QueueJobs to update.
   */
  limit?: number
}

/**
 * QueueJob upsert
 */
export type QueueJobUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * The filter to search for the QueueJob to update in case it exists.
   */
  where: Prisma.QueueJobWhereUniqueInput
  /**
   * In case the QueueJob found by the `where` argument doesn't exist, create a new QueueJob with this data.
   */
  create: Prisma.XOR<Prisma.QueueJobCreateInput, Prisma.QueueJobUncheckedCreateInput>
  /**
   * In case the QueueJob was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QueueJobUpdateInput, Prisma.QueueJobUncheckedUpdateInput>
}

/**
 * QueueJob delete
 */
export type QueueJobDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
  /**
   * Filter which QueueJob to delete.
   */
  where: Prisma.QueueJobWhereUniqueInput
}

/**
 * QueueJob deleteMany
 */
export type QueueJobDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QueueJobs to delete
   */
  where?: Prisma.QueueJobWhereInput
  /**
   * Limit how many QueueJobs to delete.
   */
  limit?: number
}

/**
 * QueueJob without action
 */
export type QueueJobDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QueueJob
   */
  select?: Prisma.QueueJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QueueJob
   */
  omit?: Prisma.QueueJobOmit<ExtArgs> | null
}
