name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*"]
    name: Test on node@v${{ matrix.node }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: changeme
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgresql://postgres:changeme@localhost:5432/postgres?schema=public"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4
      - name: Setup node 🔧
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: "pnpm"
      - name: Install 🪄
        run: pnpm install --frozen-lockfile
      - name: Generate & push prisma schema 🪄
        run: pnpm prisma db push
      - name: Lint (oxlint) 🔍
        run: pnpm run lint
      - name: Format (oxfmt) 🔍
        run: pnpm run format:check
      - name: TypeScript 🔍
        run: pnpm run check
      - name: Vitest 🔍
        run: pnpm run spec
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*"]
    name: Build on node@v${{ matrix.node }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v4
      - name: Setup node 🔧
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: "pnpm"
      - name: Install 🪄
        run: pnpm install --frozen-lockfile
      - name: Generate prisma schema 🪄
        run: pnpm prisma generate
      - name: Build 💎
        run: pnpm run build
